package com.dalthow.etaron.utils;

/**
 * Etaron
 *
 *
 * @author Dalthow Game Studios 
 * @class LogUtils.java
 *
 **/

public class LogUtils
{
	/**	
	 * formatServerMessage Formats a message generated by the server.
	 * 
	 * @param  {String} message The unformatted String.
	 * 
	 * @return {String} 		The formatted string
	 */
	public static String formatServerMessage(String message)
	{
		return message.substring(0, 1).toUpperCase() + message.substring(1) + ".";
	}
}
